export enum AppRoutes {
  MAIN = 'main',
  AUTH = 'auth',
  NOT_FOUND_PAGE = 'not_found',
  RULES = '/rules',
  PARTNERS = '/partners',
  FEEDBACK = '/feedback',
  FOR_AUTOPARKS = '/for-autoparks',
  FOR_PARTNERS = '/for-partners',
  ABOUT_US = '/about-us',
  ORDER_STEPS = '/order-steps',
  DRIVER_FULL_DOCUMENTATION = '/driver-full-documentation',
  AUTOPARK_FULL_DOCUMENTATION = '/autopark-full-documentation',
  HOW_ADD_AUTOPARK = '/how-add-autopark',
  ADD_AUTOPARK = '',
  CONDITIONS = '/conditions',
  TEAM = '/team',
  JOB = '/job',
}
